Feature/mobile base components
InstamintG/InstamintG6 pull request #12
Opened 2024-04-22 21:53 UTC by Lucas-Senoville

Add basic components : FormInput + CustomButton

2024-04-22 21:57 UTC, loicleclere requested changes
Can you add a third color to the CustomButton for the "cancel" case?

2024-04-23 07:20 UTC, loicleclere submitted a review, later dismissed
Approve

2024-04-23 07:29 UTC, zrichard22 requested changes

2024-04-23 07:29 UTC, zrichard22 commented on mobile-app/components/UI/CustomButton.tsx
> +  if (props.color === 'primary') {
Use an object mapping instead of this conditional block

2024-04-23 07:29 UTC, zrichard22 commented on mobile-app/components/UI/CustomButton.tsx
> +  let colors
This variable is useless

2024-04-23 07:29 UTC, zrichard22 commented on mobile-app/components/UI/CustomButton.tsx
> +  color: 'primary' | 'secondary' | 'danger'
With an object mapping, you can use the keyof object instead of this 'or' types

2024-04-23 07:29 UTC, zrichard22 commented on mobile-app/components/UI/CustomButton.tsx
> +const styles = StyleSheet.create({
I think, it'll be better if the style is separate in another file

2024-04-23 07:29 UTC, zrichard22 commented on mobile-app/components/UI/CustomButton.tsx
> +    color: 'black',
Question: Can we use tamagui value instead default value (with a function that take the value of the tokens object and convert it to CSS value for example) ?

2024-04-23 07:29 UTC, zrichard22 commented on mobile-app/components/UI/CustomButton.tsx
> +const CustomButton = (props: CustomButtonProps) => {
Destructure directly in params

2024-04-23 07:29 UTC, zrichard22 commented on mobile-app/components/UI/CustomButton.tsx
> +            props.color === 'primary'
use mapping object instead this terenary condition

2024-04-23 07:33 UTC, Lucas-Senoville commented on mobile-app/components/UI/CustomButton.tsx
> +    color: 'black',
Maybe we need to create a Color.ts in the future that contains all the color variables that we use outside of tamagui components

2024-04-23 07:36 UTC, zrichard22 commented on mobile-app/components/UI/CustomButton.tsx
> +    color: 'black',
I like this idea, I create the associate technical ticket

2024-04-23 07:53 UTC, zrichard22 requested changes

2024-04-23 08:28 UTC, zrichard22 approved these changes

2024-04-23 08:29 UTC, loicleclere approved these changes
Approve

2024-04-23 08:30 UTC, merged