Feature/13 registration
InstamintG/InstamintG6 pull request #13
Opened 2024-04-28 16:47 UTC by loicleclere

2024-04-28 18:15 UTC, HugoTourneur submitted a review, later dismissed

2024-04-28 19:59 UTC, Lucas-Senoville approved these changes

2024-04-28 20:52 UTC, zrichard22 requested changes

2024-04-28 20:52 UTC, zrichard22 commented on backend/microservices/UserAccount/src/controllers/UserControllers.ts
> +      id: user.id,
Why not use spread instead assign every value to every properties of the object

2024-04-28 20:52 UTC, zrichard22 commented on backend/microservices/UserAccount/src/controllers/UserControllers.ts
> +      expires: new Date(
It can be nice if you move this logic in a function in a utils directory

2024-04-28 20:52 UTC, zrichard22 commented on backend/microservices/UserAccount/src/controllers/UserControllers.ts
> +    const { email, password }: { email: string; password: string } =
You can create a distinct type for this line instead `{ email: string; password: string }`

2024-04-28 20:52 UTC, zrichard22 commented on backend/microservices/UserAccount/src/controllers/UserControllers.ts
> +    const code = randomInt(10000, 99999).toString()
You can create an utils function here

2024-04-28 20:52 UTC, zrichard22 commented on backend/microservices/UserAccount/src/controllers/UserControllers.ts
> +      process.env.SENDGRID_TEMPLATE_CONFIRMATION_KEY || '',
Why not use the config.ts here instead a process.env directly in the controller

2024-04-28 20:52 UTC, zrichard22 commented on backend/microservices/UserAccount/src/controllers/UserControllers.ts
> +      data: {
I think it's possible to use a cleaner code here

2024-04-28 20:52 UTC, zrichard22 commented on backend/microservices/UserAccount/src/database/seed.ts
> +    const password = 'azeAZE123!!!'
You can use a constant here like PASSWORD_USER_SEED outside of the loop

2024-04-28 20:52 UTC, zrichard22 commented on backend/microservices/UserAccount/src/routes/apiRoutes.ts
> +    async (ctx: Context) => {
I think you can use a syntax like that : `() => returnValue` whithout bracket braces

2024-04-28 20:52 UTC, zrichard22 commented on backend/microservices/UserAccount/src/server.ts
> +    cors({
It can be a good pratice to use a constant here in parameter (like CORS_PARAMS)

2024-04-28 20:52 UTC, zrichard22 commented on backend/microservices/UserAccount/src/utils/mailer.ts
> +    sgMail.setApiKey(process.env.SENDGRID_API_KEY || '')
use config.ts to store env value

2024-04-28 20:52 UTC, zrichard22 commented on backend/microservices/microservice-template/src/server.ts
>      cors({
use a constant here instead directly send an object created in parameters

2024-04-28 20:52 UTC, zrichard22 commented on mobile-app/app/(auth)/_layout.tsx
> +  if (session === null) {
Use !session

2024-04-28 20:52 UTC, zrichard22 commented on mobile-app/app/_layout.tsx
> +            contentStyle: { backgroundColor: '#000000' },
Avoid use full black hex value and use a constant instead

2024-04-28 20:52 UTC, zrichard22 commented on mobile-app/app/ctx.tsx
> +export function SessionProvider(props: React.PropsWithChildren) {
Destructure props instead use props.

2024-04-28 20:52 UTC, zrichard22 commented on mobile-app/components/UI/PasswordStrengthIndicator .tsx
> +const RequirementIndicator = ({
Move this component in another file

2024-04-28 20:52 UTC, zrichard22 commented on mobile-app/components/UI/PasswordStrengthIndicator .tsx
> +  const minimumLengthMet = password.length >= 12
No magic number

2024-04-28 20:52 UTC, zrichard22 commented on mobile-app/components/UI/PasswordStrengthIndicator .tsx
> +  const hasUpperCase = /[A-Z]/.test(password)
Why not use zod in these cases ?

2024-04-28 20:52 UTC, zrichard22 commented on mobile-app/screens/register/emailVerification.tsx
> +          code &&
Move this logic in an utils function

2024-04-28 20:52 UTC, zrichard22 commented on mobile-app/screens/register/emailVerification.tsx
> +            `${process.env.EXPO_PUBLIC_USER_ACCOUNT_MICROSERVICE_URL}/api/verifyAccount`,
I think there is a better method to use the API path

2024-04-28 20:52 UTC, zrichard22 commented on mobile-app/screens/register/emailVerification.tsx
> +  const openModal = () => {
Remove brackets braces

2024-04-28 20:52 UTC, zrichard22 commented on mobile-app/screens/register/emailVerification.tsx
> +  const closeModal = () => {
Remove brackets braces

2024-04-28 20:52 UTC, zrichard22 commented on mobile-app/screens/register/emailVerification.tsx
> +import CustomSafeArea from '@/components/UI/CustomSafeArea'
Use a barrels for all ui component can be a good practice

2024-04-28 20:52 UTC, zrichard22 commented on mobile-app/screens/signin.tsx
> +type FormData = {
I think the name of the type can be more explicit

2024-04-29 20:20 UTC, Lucas-Senoville approved these changes

2024-04-29 20:25 UTC, zrichard22 commented on backend/microservices/UserAccount/src/controllers/UserControllers.ts
> +      expires: new Date(
Will be created in another PR

2024-04-29 20:26 UTC, zrichard22 commented on backend/microservices/UserAccount/src/controllers/UserControllers.ts
> +      data: {
Will be fixed in another PR

2024-04-29 20:28 UTC, zrichard22 commented on mobile-app/screens/register/emailVerification.tsx
> +import CustomSafeArea from '@/components/UI/CustomSafeArea'
Will be implemented in the future

2024-04-29 20:54 UTC, zrichard22 approved these changes
🎉

2024-04-29 21:02 UTC, loicleclere commented on mobile-app/app/_layout.tsx
> +            contentStyle: { backgroundColor: '#000000' },
It's will be fix with the CustomNavStack component

2024-04-29 21:06 UTC, Lucas-Senoville approved these changes

2024-04-29 21:23 UTC, merged