[93] Feature : Delete session when application is completely closed
InstamintG/InstamintG6 pull request #21
Opened 2024-05-04 21:20 UTC by loicleclere

2024-05-04 21:26 UTC, Lucas-Senoville submitted a review, later dismissed

2024-05-04 22:10 UTC, zrichard22 requested changes

2024-05-04 22:10 UTC, zrichard22 commented on mobile-app/app/(auth)/_layout.tsx
> +      if (!login) {
Nested if statement

2024-05-05 10:29 UTC, zrichard22 approved these changes

2024-05-05 10:35 UTC, Lucas-Senoville approved these changes

2024-05-05 10:35 UTC, merged