[17] Feature : Reset password
InstamintG/InstamintG6 pull request #22
Opened 2024-05-04 22:08 UTC by Lucas-Senoville

2024-05-04 22:23 UTC, zrichard22 requested changes

2024-05-04 22:23 UTC, zrichard22 commented on mobile-app/components/UI/ResetPasswordForm.tsx
Change file name to just PasswordForm can be a good thing

2024-05-04 22:23 UTC, zrichard22 commented on mobile-app/components/UI/ResetPasswordForm.tsx
> +const ResetPasswordForm = (resetPasswordForm: ResetPasswordForm) => {
And therefore the component name

2024-05-04 22:55 UTC, Lucas-Senoville commented on mobile-app/components/UI/ResetPasswordForm.tsx
It can be confusing to name it 'PasswordForm' because it can mean that it used everywhere there is a Password needed. Here, it clearly means that it is used to reset an already existing password.

2024-05-04 22:57 UTC, zrichard22 commented on mobile-app/components/UI/ResetPasswordForm.tsx
You can name it ChangePasswordForm or something like that

2024-05-05 11:05 UTC, zrichard22 approved these changes

2024-05-05 11:46 UTC, loicleclere approved these changes
Approve

2024-05-05 11:46 UTC, merged